version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: dockers/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../api:/app
      - ../queues:/queues
      - ../train:/train
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
